#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("KOTUS.Resource", IsApplication=true)]

namespace KOTUS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060002
			public const int DashOptArr = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int GroupOptArr = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int LoginArray = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int privacy_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int my_orange = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawer_shadow_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int error = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int kotus_splash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int kotusLogoTrans = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int splash = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080014
			public const int Description = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int DescriptionText = 2131230741;
			
			// aapt resource value: 0x7f08000b
			public const int EndDate = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int EndTime = 2131230737;
			
			// aapt resource value: 0x7f080006
			public const int Location = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int StartDate = 2131230728;
			
			// aapt resource value: 0x7f08000e
			public const int StartTime = 2131230734;
			
			// aapt resource value: 0x7f080004
			public const int Title = 2131230724;
			
			// aapt resource value: 0x7f080018
			public const int author = 2131230744;
			
			// aapt resource value: 0x7f080000
			public const int button1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int button2 = 2131230721;
			
			// aapt resource value: 0x7f08002a
			public const int calendarButton = 2131230762;
			
			// aapt resource value: 0x7f080002
			public const int calendarView1 = 2131230722;
			
			// aapt resource value: 0x7f080021
			public const int cancel = 2131230753;
			
			// aapt resource value: 0x7f080041
			public const int confirmPass = 2131230785;
			
			// aapt resource value: 0x7f08001b
			public const int content = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int content_frame = 2131230749;
			
			// aapt resource value: 0x7f080038
			public const int create = 2131230776;
			
			// aapt resource value: 0x7f080016
			public const int createEvent = 2131230742;
			
			// aapt resource value: 0x7f080033
			public const int date = 2131230771;
			
			// aapt resource value: 0x7f08000c
			public const int dateDisplayEnd = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int dateDisplayStart = 2131230729;
			
			// aapt resource value: 0x7f080019
			public const int datetime = 2131230745;
			
			// aapt resource value: 0x7f080022
			public const int delete = 2131230754;
			
			// aapt resource value: 0x7f08001c
			public const int drawer_layout = 2131230748;
			
			// aapt resource value: 0x7f080036
			public const int edit = 2131230774;
			
			// aapt resource value: 0x7f080034
			public const int editContent = 2131230772;
			
			// aapt resource value: 0x7f080020
			public const int editEvent = 2131230752;
			
			// aapt resource value: 0x7f080025
			public const int editText1 = 2131230757;
			
			// aapt resource value: 0x7f08002f
			public const int editText2 = 2131230767;
			
			// aapt resource value: 0x7f080032
			public const int editTitle = 2131230770;
			
			// aapt resource value: 0x7f08003a
			public const int firstName = 2131230778;
			
			// aapt resource value: 0x7f080039
			public const int firstNameLabel = 2131230777;
			
			// aapt resource value: 0x7f080028
			public const int groupCreateButton = 2131230760;
			
			// aapt resource value: 0x7f080027
			public const int groupName = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int groupNameLabel = 2131230758;
			
			// aapt resource value: 0x7f080023
			public const int imageView1 = 2131230755;
			
			// aapt resource value: 0x7f08002b
			public const int inviteButton = 2131230763;
			
			// aapt resource value: 0x7f08003c
			public const int lastName = 2131230780;
			
			// aapt resource value: 0x7f08003b
			public const int lastNameLabel = 2131230779;
			
			// aapt resource value: 0x7f08001e
			public const int left_drawer = 2131230750;
			
			// aapt resource value: 0x7f080030
			public const int linearLayout1 = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int linearLayout2 = 2131230769;
			
			// aapt resource value: 0x7f080003
			public const int listView1 = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int locationText = 2131230727;
			
			// aapt resource value: 0x7f08002c
			public const int membersButton = 2131230764;
			
			// aapt resource value: 0x7f080029
			public const int messageButton = 2131230761;
			
			// aapt resource value: 0x7f080017
			public const int messageRow = 2131230743;
			
			// aapt resource value: 0x7f08003e
			public const int phone = 2131230782;
			
			// aapt resource value: 0x7f08003d
			public const int phoneNumberLabel = 2131230781;
			
			// aapt resource value: 0x7f08000d
			public const int pickDateEnd = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int pickDateStart = 2131230730;
			
			// aapt resource value: 0x7f080013
			public const int pickTimeEnd = 2131230739;
			
			// aapt resource value: 0x7f080010
			public const int pickTimeStart = 2131230736;
			
			// aapt resource value: 0x7f08002d
			public const int progressBar1 = 2131230765;
			
			// aapt resource value: 0x7f08001a
			public const int replyRow = 2131230746;
			
			// aapt resource value: 0x7f080035
			public const int submit = 2131230773;
			
			// aapt resource value: 0x7f08001f
			public const int tableRow1 = 2131230751;
			
			// aapt resource value: 0x7f080024
			public const int textView1 = 2131230756;
			
			// aapt resource value: 0x7f08002e
			public const int textView2 = 2131230766;
			
			// aapt resource value: 0x7f080037
			public const int textView3 = 2131230775;
			
			// aapt resource value: 0x7f080012
			public const int timeDisplayEnd = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int timeDisplayStart = 2131230735;
			
			// aapt resource value: 0x7f080005
			public const int title = 2131230725;
			
			// aapt resource value: 0x7f08003f
			public const int userEmail = 2131230783;
			
			// aapt resource value: 0x7f080040
			public const int userPass = 2131230784;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdminDash = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Calendar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateCalenderEvent = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int customMessageRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int customReplyRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DrawerLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DrawerListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int EditCalenderEvent = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int exampleListGroup = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ForgotPass = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int GroupCreate = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int GroupDash = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Loading = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Login = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int mBoard = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MessageEdit = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int MessageView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int MessageWrite = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int signUp = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int UserCalendar = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int UserDash = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int DrawerClose = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int DrawerOpen = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int privacy = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyCustomTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int buttonStyle = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int groupNameStyle = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
